### ISSUE TITLE
create invoice with context crashed

### ISSUE THREAD

**Issue by ragnarok22** [TelePay-cash/telepay-python#14]
**Describe the bug**
Telepay client crashes when is used with context (`with`)

**To Reproduce**

    with TelePaySyncClient(secret_api_key=settings.TELEPAY_SECRET_API_KEY) as client:
        return client.create_invoice(
            asset=asset,
            blockchain=blockchain,
            network=network,
            description=description,
            amount=amount,
            success_url=success_url,
            cancel_url=cancel_url,
            expires_at=10
        )
This raised:

    TypeError: __exit__() takes 1 positional argument but 4 were given

Acording with the [documentation](https://docs.python.org/3/reference/datamodel.html#object.__exit__) `__exit__` takes the self parameter and three extra parameters describing an error if one was raised, otherwise they are all set to `None`. I think the error is in [this line](https://github.com/TelePay-cash/telepay-python/blob/d9ad8dc31dd1328e29b89b2294eefb1c1fdaa4be/telepay/v1/_sync/client.py#L37)

**Comment by CarlosLugones** [comment]
Positional arguments were missing on the sync client's `__exit__` method. Fix coming up.
